### ISSUE TITLE
Lambda: ecs-lifecycle-hook-terminate.py Raising exception

### ISSUE THREAD

**Issue by ethicalmohit** [awslabs/ecs-cluster-manager#1]
I have set up a cloud watch event rule with a rule just with lambda responsible for ec2 terminating lifecycle but I am getting below error.

```
 START RequestId: c388ff12-950f-49dc-a4e0-1d9b0bdf7417 Version: $LATEST
Recieved event
{
    "version": "0",
    "id": "cc9dc08f-16bd-8f36-ad8f-410a8a74706f",
    "detail-type": "EC2 Instance-terminate Lifecycle Action",
    "source": "aws.autoscaling",
    "account": "account-id",
    "time": "2019-04-30T18:25:56Z",
    "region": "us-east-1",
    "resources": [
        "arn:aws:autoscaling:us-east-1:account-id:autoScalingGroup:5532977d-22a7-4b06-b33a-3b0e0e29ba94:autoScalingGroupName/EC2ContainerService-testing-EcsInstanceAsg-E1YSQ3BF4NGK"
    ],
    "detail": {
        "LifecycleActionToken": "96876f0e-aa5b-48f1-92e4-4305b739792a",
        "AutoScalingGroupName": "EC2ContainerService-testing-EcsInstanceAsg-E1YSQ3BF4NGK",
        "LifecycleHookName": "clusterDrain",
        "EC2InstanceId": "i-04f772f7d7cba97ed",
        "LifecycleTransition": "autoscaling:EC2_INSTANCE_TERMINATING"
    }
}

Recieved Lifecycle Hook message
{
    "LifecycleActionToken": "96876f0e-aa5b-48f1-92e4-4305b739792a",
    "AutoScalingGroupName": "EC2ContainerService-testing-EcsInstanceAsg-E1YSQ3BF4NGK",
    "LifecycleHookName": "clusterDrain",
    "EC2InstanceId": "i-04f772f7d7cba97ed",
    "LifecycleTransition": "autoscaling:EC2_INSTANCE_TERMINATING"
}

Determining our ECS Cluster name . . .
Exception: cannot use a string pattern on a bytes-like object
END RequestId: c388ff12-950f-49dc-a4e0-1d9b0bdf7417
```

I have not followed whole architecture, as I only wanted to use the lambda with the termination lifecycle of the ec2 instance.

Is it a known issue?

**Comment by chirillc-aws** [comment]
Hi @ethicalmohit, thank you reporting this issue!
In order for the lambda to work properly, the EC2 instance needs to be  part of ECS cluster. This is derived from the EC2 user-data which contains a command to inject the cluster name into ECS agent config files. Lambda is using the following regular expression search pattern: "ECS_CLUSTER\s?=\s?(.*?)\s" against user data script to figure it out.
On failure lambda raises an exception which means this instance isn't a ECS cluster member so ASG can proceed with termination. 

In case you'd like to test this solution end-to-end, please follow steps described here:
https://aws.amazon.com/blogs/compute/automatically-update-instances-in-an-amazon-ecs-cluster-using-the-ami-id-parameter/

**Comment by ethicalmohit** [comment]
The instance is obviously the part of the ECS cluster.

It works after changing the code as below.
Line 42: ` clustername = re.search("ECS_CLUSTER\s?=\s?(.*?)\s", str(userdata))`

**Comment by chirillc-aws** [comment]
@ethicalmohit thank you for pointing it out and providing the solution. The change has been merged into master branch.
